### ISSUE TITLE
Untrusted users are able to remove armor from Armor Stand

### ISSUE THREAD

**Issue by barrettford** [aleksilassila/Islands#11]
Untrusted, non-op users are able to remove armor from an armor stand, even when they can't interact with anything else on the island.

**Comment by aleksilassila** [comment]
What do you think, should players only be able to interact with armor stands if they have build access? Or would container access do?

**Comment by barrettford** [comment]
I feel that armor stands are containers.

**Comment by aleksilassila** [comment]
Fixed in next patch
