### ISSUE TITLE
Non-trusted players are able to interact with barrels

### ISSUE THREAD

**Issue by barrettford** [aleksilassila/Islands#13]
Even with container protection enabled.

Non-trusted players can also interact with minecart chests and enter/exit/move/place/remove minecarts.

I guess barrels would be alright to leave interactable, so that you can have a drop box of sorts for your island.  It's not common to use barrels much, however I can imagine that someone would be surprised to find that barrels (containers) are still interactable by non-trusted people without container trust turned on.

**Comment by barrettford** [comment]
My kid was also able to steal all of the coal out of my smoker, even though he doesn't have trust on my island.

**Comment by aleksilassila** [comment]
Container trust fixed for barrels and smokers, also fixed tnt ignition and minecarts. Decided to let people still move the minecarts.
