### ISSUE TITLE
wilderness change back to hard difficulty.

### ISSUE THREAD

**Issue by DarkWolfNL611** [aleksilassila/Islands#20]
Hello,

We are using the Island plugin and are really happy with it!
Unfortunately some of our players would like to play on normal difficulty.
We looked into this and found out that the plugin generates the wilderness world on hard difficulty and there are no options to change this...

Would it be possible to get a config file entry to customize the world difficulty?

**Comment by monkeyno0dle** [comment]
If you are using the multiverse plugin, (which if you're not I would highly recommend) you can use the command /mvmset difficulty normal. This worked just fine for me. If you arent using multiverse you should just be able to do /difficulty normal for the whole server.

**Comment by DarkWolfNL611** [comment]
i do have it and i can set it to normal but after a reset it change back because of the script

**Comment by j4c3** [comment]
Every time I start the server, I see this: 

[12:09:45 INFO]: [Islands] Islands source world set to islandsSource
[12:09:45 INFO]: [Islands] No wilderness found. Creating one called wilderness...
[12:09:45 INFO]: Preparing start region for dimension minecraft:wilderness
[12:09:45 INFO]: Loaded 0 spawn chunks for world wilderness
[12:09:45 INFO]: Preparing spawn area: 0%
[12:09:46 INFO]: Preparing spawn area: 9%
[12:09:46 INFO]: Preparing spawn area: 9%
[12:09:46 INFO]: Time elapsed: 1192 ms
[12:09:46 INFO]: [Islands] Using English locales
[12:09:46 INFO]: [Islands] Islands enabled!

But, wilderness exists, has existed, and I've been to it.  So, it may not be detecting it is there, and recreating it and overwriting your change to the difficulty.

**Comment by aleksilassila** [comment]
I did some testing and seems like after changing wilderness to peaceful with /difficulty peaceful and restarting, the apparent difficulty is back to hard, but no mobs spawn or can be spawned until the difficulty is set back to > easy. So the actual difficulty is still peaceful after a restart even though /difficulty says  it's back to hard, if that makes sense. A little inconvenient, but shouldn't affect gameplay.

**Comment by aleksilassila** [comment]
Found a fix for this, will be completely fixed in next update.
