### ISSUE TITLE
Wrong home

### ISSUE THREAD

**Issue by Redstylt** [aleksilassila/Islands#24]
Hello,

I found an issue with the /home.
EDIT : just realize it's quite the same isssue [here #22 ](https://github.com/aleksilassila/Islands/issues/22) but i cleared my island...It should fix than

Situation : 
1* I created a test server (with just few essentials plugins : EssentialsX, Vault, LP, Islands)
2* I connected to my server and create my island
3* I stopped the server and changed the island world name to IslandsWorld
4* I restarted the server, cleared my island, created again
5* I teleported myself with a /home but I appeared like 100 blocks away from my island...In the void....

Expected solution : 
The home is reset at creation of the island to prevent to be teleported on a previous location.
Blocked the /home until the island is 100% generated to avoid to fall in the void

Hope everything is clear

**Comment by aleksilassila** [comment]
The plugin keeps track of all the islands using plugins/Islands/islands.yml file. If you delete your islands world or change the islands manually without using the plugin's commands, the plugin has no way of knowing that where there was previously an island and a home, don't exist any more. 

So, when you clear or change your islands world to a new empty one, make sure to delete the old islands.yml file. That way your old homes don't exist where there isn't actually islands. To fix the home that teleports you over the void, teleport to the home in creative and when standing over the missing island, use /is recreate or /is remove to update the island. 

Let me know if this helps, I hope this was the problem

Cheers
