### ISSUE TITLE
Players can use /home before island finished generating.

### ISSUE THREAD

**Issue by ElMoha943** [aleksilassila/Islands#26]
As the title says, this is a problem because people fall into void, if you dont have the tp to wilderness option on true they will die.

**Comment by aleksilassila** [comment]
There's a setting called `unfinishedIslandTeleports` in config.yml that can prevent this. Let me know if there are issues with this

**Comment by ElMoha943** [comment]
yeah i have it on but it doesnt seem to work properly, im running tuinity 1.16.5 with plugins lastets version.
