### ISSUE TITLE
[SUGGESTION] Customizable messages.

### ISSUE THREAD

**Issue by ElMoha943** [aleksilassila/Islands#27]
I would love if you could add a messages.txt so we ca translate and change messages formats as we like.

**Comment by aleksilassila** [comment]
You can already customize all the messages, check https://github.com/aleksilassila/Islands/wiki/Messages-And-Locales

**Comment by ElMoha943** [comment]
I see, it would be nice to have at least messages_en by default so it would be more evident. Also i would like &colorcodes support instead of the weird minecraft system.

**Comment by aleksilassila** [comment]
This is the way most plugins like essentials do it 🤷‍♂️ anyways, escaping the § unicode symbol in messages isn't up to me, that's just how java locales work I guess. Inconvenient, I know

**Comment by ElMoha943** [comment]
> This is the way most plugins like essentials do it 🤷‍♂️ anyways, escaping the § unicode symbol in messages isn't up to me, that's just how java locales work I guess. Inconvenient, I know

Actually most popular ones convert the color codes but its ok

**Comment by aleksilassila** [comment]
They do? Now that I think about it, that might not be that complicated. Oh well
