### ISSUE TITLE
Vault Support

### ISSUE THREAD

**Issue by DeanGrey** [aleksilassila/Islands#4]
If I shouldn't be submitting suggestions here, I apologize. I think Vault support for buying different sized islands would be ideal. Each size could have its own price configuration.

Perhaps purchasable in a GUI? That's just preference though.

**Comment by aleksilassila** [comment]
No worries, this is fine. I agree, that would inded be a good feature and I'll add that to my todo list. Working on some general gui classes so once those are done I might add more gui stuff in general to the plugin.
