### ISSUE TITLE
Water and Lava Flow outside island realm disabled?

### ISSUE THREAD

**Issue by AstralNomadED** [aleksilassila/Islands#5]
Setting up a new server and my idea was centered around the islands plugin as a core server mechanic.  Couple of days into the server test phase, a bug was reported to me.  It seems that water and lava work as they should no the islands, but both naturally spawning and bucket placed water and lava source blocks in the wilderness, nether, end, and any other world do not spread.  The source block just sits there.  Water will not regen source blocks either.  I had begun to remove other plugins and data packs, check config files.  Nothing seemed to fix the problem.  Today, I removed the islands.jar file and loaded the server.  I jumped off and died (expected), used a portal to access the nether, and now lava spreads properly in the nether at least.  Any ideas?

**Comment by AstralNomadED** [comment]
Just downloaded and installed the 4.5.3 update.  Was still using the 4.5.0 file.  Seems to fix the flow issue, but all of the islands have been unassigned.

**Comment by aleksilassila** [comment]
Thanks for reporting, I found the bug and I will patch it as soon as I get home. Looks like I reintroduced it with the restriction configuration update (IslandsListener.java:39)

Cheers

**Comment by AstralNomadED** [comment]
Thanks for responding so quick.  I was worried that I was going to have to make schematics of every island and reset.  The 'UUID' and 'trusted' lines in the islands.yml for each island are still there and matching the info in the playerdata folder.   When I log in after updating the islands.jar, typing  /homes returns with 'Found 0 home(s)'.  Luckily, the isSpawn still works and all the islands are physically there.

**Comment by aleksilassila** [comment]
Describe your second problem again; are you for example restricted from interacting with the islands when you dont have bypass permissions? What else is wrong with the islands?

**Comment by AstralNomadED** [comment]
Sure.  Updated from 4.5.0 to 4.5.3.   Log on and spawn at island marked with isSpawn: true.  Previously owned 3 islands myself, now showing 0 owned when I enter /homes.  Also cannot /visit any islands previously owned and named by myself or others.  Islands are still in the islands.yml and the islands blocks are present in the world.  Can only interact with op permissions.  Otherwise, even on my own island, message states that I don't have permission from the owner to interact with the island.

**Comment by AstralNomadED** [comment]
It is acting in game as though islands that were created before the update are now no longer owned by anyone.  However, the UUID in the islands.yml as well as the trusted ids are still listed.
![Screenshot_5](https://user-images.githubusercontent.com/73569848/97419425-4891b800-18c7-11eb-9c01-6951806efa78.jpg)

**Comment by AstralNomadED** [comment]
/homes = Found 0 homes(s).
/home = [Error] 404 - Home not found :(
/visit welcome = 'An internal error occurred while attempting to perform this command' - This island was/is owned by me

**Comment by aleksilassila** [comment]
Was due to islands.yml containing old values from earlier plugin versions. Flow issue is now patched.
