### ISSUE TITLE
Reprint Request

### ISSUE THREAD

**Issue by JeansouLiu** [aleksilassila/Islands#7]
Can I reprint this plugin to a Chinese Minecraft forum called [MCBBS](https://www.mcbbs.net) and translate the descriptions into Chinese?
**I will place your credit and the spigotmc.org page link in the reprinted page.**
I believe many people will like this plugin.

**Comment by aleksilassila** [comment]
Sure, that would be great! Also, a Chinese translation of the plugin would come in handy too, if you are interested of course. It can be a bit time consuming though, so no pressure :)

Cheers
