### ISSUE TITLE
Home command not cascading to remaining islands.

### ISSUE THREAD

**Issue by barrettford** [aleksilassila/Islands#9]
Recreate bug:  Create 2 islands.  Give away first island.  /home command claims you have no home.
Workaround:  Use /home 2 all the time instead of just /home.

It would be nice if the home command would automatically pick your lowest-indexed home.  Or, better yet, if you could declare which home the default /home command should point at.

<img width="499" alt="Screen Shot 2020-11-09 at 10 38 55 AM" src="https://user-images.githubusercontent.com/6371156/98576621-09c11200-2278-11eb-8a36-ad027b37cda0.png">

**Comment by aleksilassila** [comment]
Fixed in next release, thanks for reporting
